### ISSUE TITLE
Required write-speed for RT-DC

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/rtdc_hdf5#4]
@phidahl 
I wrote a test method to see how hdf5 could perform for RT-DC measurements. Writing 20000 events of a 256x256 uint8 array and two other columns takes approximately 3s using h5py. I observed that writing 10 events at a time is faster than writing 1 event at a time:
https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/blob/master/Python/rtdc_writer.py
(executing the file creates a 1.3 GB hdf5 file named "test_rt.rtdc").

Is this in principle fast enough for real-time measurements?

I guess that using the C++ libraries (without the Python sugar) might lead to additional speed-up.

**Comment by phidahl** [comment]
@paulmueller This is great! 2000 events/s already would be sufficient. At the moment I don't have time to look into it, but after next week I can see how to implement a writer in C++. This will be part of a new ShapeIn version in the future.
