### ISSUE TITLE
hdf5 column names

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/rtdc_hdf5#5]
@phidahl 
I vote for better column names than those in the tdms file format (e.g. time vs frame) and better metadata readability (e.g. always with units in square brackets or some such). I would like to use these as default column names and config keys in dclab.
See also issues
- https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/8
- https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/16

Any thoughts on this?

**Comment by paulmueller** [comment]
@phidahl 
I added the file columns.py that I would like to use to replace dclab.definitions:
https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/blob/master/Python/columns.py
I made the column names a little bit more descriptive. A few things are still unclear to me (marked with comments).
Once we agree on the column names here, I will implement them in dclab.

**Comment by paulmueller** [comment]
We will not need the `userdef` columns, as dclab will be able to handle unknown columns in the future (see https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/16).

**Comment by phidahl** [comment]
Hi,

I'm fine with the suggested column names.
fc0 columns can be thrown out. They are deprecated and have not been used for years.

In the hdf5 performance test you save the images as a 3-dimensinal table which gets huge.
I'm going to find out if it's better to write separate 2D arrays, or maybe stack the 3D array differently..

Here is also a description what meta-data to put, in order to make the images visible for the standard hdf5 reader HDFView.
https://stackoverflow.com/questions/29724553/add-raster-image-to-hdf5-file-using-h5py

**Comment by paulmueller** [comment]
I changed the example to match a more realistic scenario (https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/blob/master/Python/rtdc_writer.py):
- image size: 250x80
- event number: 11440
The resulting hdf5 file (230 MB, takes about 1s) is 1MB smaller than the .avi file of a reference data set with the same parameters. 

Hdf5 also offers compression (which we could use in a post-processing step, if the performance hit is too large).

If it is possible, I would like to stick with a chunked 3D Dataspace for video data (see https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/issues/2). It can be memory-mapped, sliced, and indexed, which is much more convenient and faster than writing images individually. I agree that the data set should be viewable with HDFView in the end.

**Comment by phidahl** [comment]
Thanks to some attributes images can now be viewed with hdfView.
One remark: in numpy images have the dimensions (y_dim, x_dim), while points in opencv are defined as (x,y). I changed this in the np.zeros call and the assertion.
Compression would be very interesting. If it is zip, I'd expect something like 1:2.

**Comment by paulmueller** [comment]
Thanks for the update.
Could you please comment on these questions? 
- There can be several peaks for a single event. Do `fl1_area`, `fl1_pos`, and `fl1_width` correspond to the first or to the highest peak?
- How do you handle `fl1_dist` if there is only one peak? Set to `nan`?
- What is the definition of inertia ratio `m20/m02`?

**Comment by paulmueller** [comment]
@phidahl In addition to the points above,

- what is the difference between "raw inertia ratio" and "inertia ratio"?

**Comment by phidahl** [comment]
- ideally fl1_area _pos and _with correspond to the found contour.. Sometimes not, but this would be due to too high concentration of cells or other errors.
- fl1_dist is set to 0, if there is no second peak

**Comment by paulmueller** [comment]
The new column naming convention is already implemented in dclab. There is nothing to add here.
